SET SEARCH_PATH TO Olympics;

DROP VIEW IF EXISTS totalpersport CASCADE;
DROP VIEW IF EXISTS aggtps CASCADE;
DROP VIEW IF EXISTS isbestC CASCADE;
DROP VIEW IF EXISTS nobestC CASCADE;
DROP VIEW IF EXISTS besttempC CASCADE;
DROP VIEW IF EXISTS isbestS CASCADE;
DROP VIEW IF EXISTS nobestS CASCADE;
DROP VIEW IF EXISTS besttempS CASCADE;
DROP VIEW IF EXISTS bestC CASCADE;
DROP VIEW IF EXISTS bestS CASCADE;